### ISSUE TITLE
Request for V12 version

### ISSUE THREAD

**Issue by Geodragon9** [Garsondee/pf2e-roll-manager#36]
I have 2 servers.  One is still on V11.. I was able to add this to that server.. But, on my V12, I can't install it..
![image](https://github.com/Garsondee/pf2e-roll-manager/assets/43663823/afca2265-a7ee-4712-9356-a71e0a88efa4)
and if I try the latest version - https://github.com/Garsondee/pf2e-roll-manager/blob/master/module.json -- 
![image](https://github.com/Garsondee/pf2e-roll-manager/assets/43663823/e3e91240-fecc-4565-936a-6a0347ef7a0b)

**Comment by Garsondee** [comment]
https://github.com/Garsondee/pf2e-roll-manager/releases/download/v1.385/module.json

Try using this link instead.

I've moved to V12 and have confirmed that it looks like there aren't any broken functions in the module for V12. If you know how to edit the JSON you can just edit it to be for V12 and it should work as a temporary fix.

**Comment by Geodragon9** [comment]
I tried the v1.385 link you provided.. Still won't install for me.  I'm running this on a linux server, so not an easy task to manually copy it over and adjust..   
In module json, probably need to change:
"compatibility": {
    "minimum": 11,
    "verified": 11, <---- maybe also to 12?
    "maximum": 11  <---- to 12

**Comment by Truncated** [comment]
In the module configuration, right click on the module text you've downloaded and you get a dropdown menu:
![image](https://github.com/Garsondee/pf2e-roll-manager/assets/14208325/b298b84c-54b5-4bde-ac31-a35a593357bb)
Choose Edit Module, and set the values as this:
![image](https://github.com/Garsondee/pf2e-roll-manager/assets/14208325/a617be57-8d4a-47cb-bc59-89a444e7180f)
Select Edit Module button to save those settings and accept whatever it tells you.

It will still give you a warning as last verified for 11, but max 12 will allow it to run in v12 instead of being blocked.

**Comment by Grolm** [comment]
Hello the issue is with the first install : 

![image](https://github.com/Garsondee/pf2e-roll-manager/assets/7125773/51b0123c-2d90-4354-a6bc-8e8bd6e75240)

![image](https://github.com/Garsondee/pf2e-roll-manager/assets/7125773/8812ceb5-915e-4b3e-a8b7-9ef5b515cdee)

It does not install so it is impossible to edit with the UI.

Could you please make a release with the maximum version updated ?

**Comment by Garsondee** [comment]
Should now be working correctly for v12.
