### ISSUE TITLE
Failure to update on Foundry via Forge

### ISSUE THREAD

**Issue by ThomaSutra** [Garsondee/pf2e-roll-manager#59]
I host my Foundry games on the Forge. 

I have tried daily to update from 1.55 to 1.75 for 2 weeks and keep getting an error message.

![Screenshot 2024-10-10 193157](https://github.com/user-attachments/assets/eaf10649-6881-408b-9e95-5b7a69c30492)

Is there something wrong on my end?

**Comment by Garsondee** [comment]
Have you tried uninstalling it, downloading the zip file and manually installing the latest zip file?

https://github.com/Garsondee/pf2e-roll-manager/releases

There is a module.zip you can download on this page. It's been a while since I've used forge but I believe you can manually install from a zip.

I'm not 100% sure what the error is but I changed the way the version numbers work and it's possible that if you were on a version before I did that then it might not know which version to update to. I would have thought that uninstalling it entirely and then reinstalling it would get you the latest version. If that's not the case then please let me know because that means there are probably other people stuck on old versions like you.

**Comment by Garsondee** [comment]
Alternatively you can use the module.json as the manifest file to do the same thing from that release page.

**Comment by Garsondee** [comment]
Hopefully a reinstall fixed this for you.

**Comment by Mushie1** [comment]
@Garsondee Just letting you know that this has been fixed in the Forge Bazaar now.

**Comment by rikmarais** [comment]
Yup! The issue was that v1.385 (released a while ago) was showing as a higher version than v1.85 (intended highest version).
For future reference, this happened because semver considers the minor version part 385 greater than 85, so the Bazaar sorting didn't consider the true latest 1.85 as a newer version.  Using a patch e.g. 1.38.5 should get around it! (and then 38 < 85 so sorting holds true to the intention).

We've gone ahead and hidden 1.385 so it'll show 1.85 as the right latest 👍

**Comment by Garsondee** [comment]
Just checking, theoretically should this now be safe to close?
