### ISSUE TITLE
Request : Change the green button place

### ISSUE THREAD

**Issue by uniwars** [Garsondee/pf2e-roll-manager#9]
Hi, actually the green buttons shows on every tab :
![image](https://github.com/Garsondee/pf2e-roll-manager/assets/65986545/a2504e76-af94-4482-9d62-4ef1dbb6602c)
and it takes a lot of space.

Would that be possible to move it on the upper right of the canva below or above the heartbeat toggle ?
![image](https://github.com/Garsondee/pf2e-roll-manager/assets/65986545/957624f3-1e8c-4e8c-b5ac-64c6d98aeba3)

that way it would be very accessible while not taking a lot of place/interacting with other buttons and messing UI

**Comment by dumptruckman** [comment]
I think fixing #5 and also providing a macro would be a better solution. I'm not sure what adds that heartbeat toggle but since I don't have it, trying to figure out if it's there and position a new button accordingly could be tricky. Instead, with a macro, you could just add it to your hotbar or do w/e else is possible with macros.

**Comment by Garsondee** [comment]
I believe this is fixed - the dice button has been moved to the command pallette.
